#!/usr/bin/awk -f
BEGIN {
	FS="\t"
	OFS="\t"
	ORS="\n"
	chrom=1
	pos=2
	id=3
	ref=4
	alt=5
	qual=6
	filter=7
	info=8
	format=9
	samples=10
}

NR == 1 {
	printf($chrom OFS $pos OFS $ref OFS $alt)
	for (i=samples; i <= NF; i++) {
		printf(OFS $i)
	}
	printf(ORS)
}
NR > 1 {
	printf($chrom OFS $pos OFS $ref OFS $alt)
	for (i=samples; i <= NF; i++) {
		printf(OFS substr($i, 1, 3))
	}
	printf(ORS)
}
